feat/new_auth: start login page. waiting api"
codeNamesLEMFA01/frontend pull request #12
Opened 2024-09-02 14:45 UTC by kohai-fred

2024-09-02 19:59 UTC, Eolran commented on src/types/login.types.ts
> +  confirmPassword?: string
confirmPassword en optionnel ?

2024-09-07 09:30 UTC, Eolran commented on src/App.tsx
> +import DiversityComponent from "@components/DiversityComponent/DiversityComponent.tsx"
Un alias de chemin relatif ici mais pas sur les autres ?

2024-09-07 09:53 UTC, Eolran requested changes

2024-09-07 09:53 UTC, Eolran commented on src/components/auth/Login/hooks/useCheckCredentials.tsx
> +    confirmPassword: "",
Pourquoi ?

2024-09-07 09:53 UTC, Eolran commented on src/components/layout/SectionLayout.tsx
Pas de dossiers Interfaces du coup ?

2024-09-07 09:53 UTC, Eolran commented on src/hooks/useRandomIntervalNames.tsx
> +}
Up

2024-09-07 09:53 UTC, Eolran commented on src/utils/auth/storageMessage.ts
> +}
Ou est-ce que c'est utilisé ? Je n'ai pas trouvé

2024-09-07 10:05 UTC, kohai-fred commented on src/App.tsx
> +import DiversityComponent from "@components/DiversityComponent/DiversityComponent.tsx"
auto import

2024-09-07 10:07 UTC, kohai-fred commented on src/components/auth/Login/hooks/useCheckCredentials.tsx
> +    confirmPassword: "",
pourquoi pas???😂
effectivement j'en avais marre de retaper tjs les credentials pour les test.
bien vu

2024-09-13 19:13 UTC, Eolran approved these changes

2024-09-14 00:54 UTC, merged